package Forms;

import javax.swing.plaf.basic.BasicInternalFrameUI;

public class AllBooks extends javax.swing.JInternalFrame {
    
    public AllBooks() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnBook1 = new javax.swing.JButton();
        btnBook2 = new javax.swing.JButton();
        btnBook3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnBook4 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnBook5 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnBook6 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        btnBook7 = new javax.swing.JButton();
        btnBook8 = new javax.swing.JButton();
        btnBook9 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        btnBook10 = new javax.swing.JButton();
        btnBook11 = new javax.swing.JButton();
        btnBook12 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 247, 247));
        setPreferredSize(new java.awt.Dimension(473, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/fiction-sting.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/fiction-the-magicians.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/fiction-white-queen.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 100, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/history-battle-cry-of-freedom.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 150));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/history-burn-my-heart.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, 150));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/history-europe.jpg"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, 150));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/romance-one-last-stop.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 850, 100, 150));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/romance-people-we-meet-on-vacation.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 850, 100, 150));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/romance-the-soulmate-equation.jpg"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 850, 100, 150));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/science-the-god-equation.jpg"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1200, 100, 150));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/science-the-premonition.jpg"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1200, 100, 150));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/science-under-a-white-sky.jpg"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1200, 100, 150));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel14.setText("Sting");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 30));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel15.setText("by Sanda Brown");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("₱275");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel17.setText("The Magicians");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, 30));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel18.setText("by Lev Grossman");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText("₱675");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 40, -1));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel20.setText("The White Queen");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, 30));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel21.setText("by Philippa Gregory");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 102, 0));
        jLabel22.setText("₱485");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        btnBook1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook1.setForeground(new java.awt.Color(0, 51, 153));
        btnBook1.setText("ADD TO CART");
        btnBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, 30));

        btnBook2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook2.setForeground(new java.awt.Color(0, 51, 153));
        btnBook2.setText("ADD TO CART");
        btnBook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 90, 30));

        btnBook3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook3.setForeground(new java.awt.Color(0, 51, 153));
        btnBook3.setText("ADD TO CART");
        btnBook3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBook3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 90, 30));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel23.setText("Battle Cry of");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, 30));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel24.setText("Freedom: The Civil");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, -1, 30));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel25.setText("War Era by James M. ");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, -1, 30));

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel26.setText("Mcpherson");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 694, -1, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 102, 0));
        jLabel27.setText("₱275");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, -1, -1));

        btnBook4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook4.setForeground(new java.awt.Color(0, 51, 153));
        btnBook4.setText("ADD TO CART");
        btnBook4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, 90, 30));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel28.setText("Burn My Heart at");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, -1, 30));

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel29.setText("Wounded Knee");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, -1, 30));

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel30.setText("by Dee Brown");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, -1, 30));

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 102, 0));
        jLabel31.setText("₱750");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 694, -1, 30));

        btnBook5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook5.setForeground(new java.awt.Color(0, 51, 153));
        btnBook5.setText("ADD TO CART");
        btnBook5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 760, 90, 30));

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel32.setText("Europe: A History");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, -1, 30));

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel33.setText("by Norman Davies");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 654, -1, 20));

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 102, 0));
        jLabel34.setText("₱395");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 680, -1, 20));

        btnBook6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook6.setForeground(new java.awt.Color(0, 51, 153));
        btnBook6.setText("ADD TO CART");
        btnBook6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 760, 90, 30));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel35.setText("One Last Stop");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1000, -1, 30));

        jLabel36.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel36.setText("by Casie McQuiston");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1020, -1, 30));

        jLabel37.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel37.setText("People We Meet");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1000, -1, 30));

        jLabel38.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel38.setText("on Vacation");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1020, -1, 30));

        jLabel39.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel39.setText("by Emily Henry");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1050, -1, -1));

        jLabel40.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel40.setText("The Soulmate");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1000, -1, 30));

        jLabel41.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel41.setText("Equation");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1020, -1, 30));

        jLabel42.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel42.setText("by Christina Lauren");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1044, -1, 30));

        jLabel43.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 102, 0));
        jLabel43.setText("₱540");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1050, 40, 30));

        jLabel44.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 102, 0));
        jLabel44.setText("₱520");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1070, -1, 30));

        jLabel45.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 102, 0));
        jLabel45.setText("₱680");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1070, -1, 30));

        btnBook7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook7.setForeground(new java.awt.Color(0, 51, 153));
        btnBook7.setText("ADD TO CART");
        btnBook7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1120, 90, 30));

        btnBook8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook8.setForeground(new java.awt.Color(0, 51, 153));
        btnBook8.setText("ADD TO CART");
        btnBook8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1120, 90, 30));

        btnBook9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook9.setForeground(new java.awt.Color(0, 51, 153));
        btnBook9.setText("ADD TO CART");
        btnBook9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook9ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1120, 90, 30));

        jLabel46.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel46.setText("The God Equation");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1350, -1, 30));

        jLabel47.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel47.setText("by Michio Kaku");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1370, -1, 40));

        jLabel49.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel49.setText("The Premonition:");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1350, -1, 30));

        jLabel50.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel50.setText("A Pandemic Story");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1380, -1, 20));

        jLabel51.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel51.setText("by Michael Lewis");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1400, -1, 30));

        jLabel52.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel52.setText("Under a White Sky");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1350, -1, 30));

        jLabel53.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel53.setText("The Nature of");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1380, -1, 20));

        jLabel54.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel54.setText("the Future");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1400, -1, 20));

        jLabel55.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel55.setText("by Elizabeth Kolbert");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1420, -1, 30));

        jLabel56.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 102, 0));
        jLabel56.setText("₱730");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1410, -1, 30));

        jLabel57.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 102, 0));
        jLabel57.setText("₱710");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1430, -1, 30));

        jLabel58.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 102, 0));
        jLabel58.setText("₱650");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1440, -1, 40));

        btnBook10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook10.setForeground(new java.awt.Color(0, 51, 153));
        btnBook10.setText("ADD TO CART");
        btnBook10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook10ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1490, 90, 30));

        btnBook11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook11.setForeground(new java.awt.Color(0, 51, 153));
        btnBook11.setText("ADD TO CART");
        btnBook11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook11ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1490, 90, 30));

        btnBook12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 9)); // NOI18N
        btnBook12.setForeground(new java.awt.Color(0, 51, 153));
        btnBook12.setText("ADD TO CART");
        btnBook12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBook12ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1490, 90, 30));

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("---");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1570, 30, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook1ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK1");
        MainMenuUI.showPanel(MainMenuUI.pnlItem1, MainMenuUI.itemQty1);
    }//GEN-LAST:event_btnBook1ActionPerformed

    private void btnBook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook2ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK2");
        MainMenuUI.showPanel(MainMenuUI.pnlItem2, MainMenuUI.itemQty2);
    }//GEN-LAST:event_btnBook2ActionPerformed

    private void btnBook3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook3ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK3");
        MainMenuUI.showPanel(MainMenuUI.pnlItem3, MainMenuUI.itemQty3);
    }//GEN-LAST:event_btnBook3ActionPerformed

    private void btnBook4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook4ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK4");
        MainMenuUI.showPanel(MainMenuUI.pnlItem4, MainMenuUI.itemQty4);
    }//GEN-LAST:event_btnBook4ActionPerformed

    private void btnBook5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook5ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK5");
        MainMenuUI.showPanel(MainMenuUI.pnlItem5, MainMenuUI.itemQty5);
    }//GEN-LAST:event_btnBook5ActionPerformed

    private void btnBook6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook6ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK6");
        MainMenuUI.showPanel(MainMenuUI.pnlItem6, MainMenuUI.itemQty6);
    }//GEN-LAST:event_btnBook6ActionPerformed

    private void btnBook7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook7ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK7");
        MainMenuUI.showPanel(MainMenuUI.pnlItem7, MainMenuUI.itemQty7);
    }//GEN-LAST:event_btnBook7ActionPerformed

    private void btnBook8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook8ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK8");
        MainMenuUI.showPanel(MainMenuUI.pnlItem8, MainMenuUI.itemQty8);
    }//GEN-LAST:event_btnBook8ActionPerformed

    private void btnBook9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook9ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK9");
        MainMenuUI.showPanel(MainMenuUI.pnlItem9, MainMenuUI.itemQty9);
    }//GEN-LAST:event_btnBook9ActionPerformed

    private void btnBook10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook10ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK10");
        MainMenuUI.showPanel(MainMenuUI.pnlItem10, MainMenuUI.itemQty10);
    }//GEN-LAST:event_btnBook10ActionPerformed

    private void btnBook11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook11ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK11");
        MainMenuUI.showPanel(MainMenuUI.pnlItem11, MainMenuUI.itemQty11);
    }//GEN-LAST:event_btnBook11ActionPerformed

    private void btnBook12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBook12ActionPerformed
        // TODO add your handling code here:
        System.out.println("BOOK12");
        MainMenuUI.showPanel(MainMenuUI.pnlItem12, MainMenuUI.itemQty12);
    }//GEN-LAST:event_btnBook12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook1;
    private javax.swing.JButton btnBook10;
    private javax.swing.JButton btnBook11;
    private javax.swing.JButton btnBook12;
    private javax.swing.JButton btnBook2;
    private javax.swing.JButton btnBook3;
    private javax.swing.JButton btnBook4;
    private javax.swing.JButton btnBook5;
    private javax.swing.JButton btnBook6;
    private javax.swing.JButton btnBook7;
    private javax.swing.JButton btnBook8;
    private javax.swing.JButton btnBook9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
