
package Forms;

import java.awt.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.JOptionPane;


public class CheckoutForm extends javax.swing.JFrame {

    ButtonGroup paymentMethods = new ButtonGroup();
    JPanel[] pnlItem;
    JLabel[] itemQty, itemPrices, bookNames;
    
    MainMenuUI main;
    
    String name, date, paymentMethod, address;
    ArrayList<String> bookOrders = new ArrayList<>();
    
    boolean isDone;
   
    public CheckoutForm(MainMenuUI main) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Checkout");
        
        this.main = main;
        isDone = false;
        
        paymentMethods.add(rbtnVisa);
        paymentMethods.add(rbtnMastercard);
        paymentMethods.add(rbtnGcash);
        
        // responsible for getting the components inside the pnlItemList 
        for (Component c : pnlItemList.getComponents())
            c.setVisible(false);
        
        // 
        pnlItem = new JPanel[]{pnlItem1, pnlItem2, pnlItem3, pnlItem4, pnlItem5, pnlItem6, 
            pnlItem7, pnlItem8, pnlItem9, pnlItem10, pnlItem11, pnlItem12};
        
        itemQty = new JLabel[]{itemQty1, itemQty2, itemQty3, itemQty4, itemQty5, itemQty6, 
            itemQty7, itemQty8, itemQty9, itemQty10, itemQty11, itemQty12};
        
        itemPrices = new JLabel[]{itemPrice1, itemPrice2, itemPrice3, itemPrice4, itemPrice5, itemPrice6, 
            itemPrice7, itemPrice8, itemPrice9, itemPrice10, itemPrice11, itemPrice12};
        
        bookNames = new JLabel[]{bookName1, bookName2, bookName3, bookName4, bookName5, bookName6, 
            bookName7, bookName8, bookName9, bookName10, bookName11, bookName12};
        
        updateListOfItems();
    }
    
    // THIS
    
    public void updateListOfItems(){
        lblNumOfItems.setText(String.format("Items (%s)", MainMenuUI.numOfItems.getText()));
        
        if (Integer.valueOf(MainMenuUI.numOfItems.getText()) > 4)
            jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        
        int i = 0, j = 0, price, qty; //i is for what panel to show, j is for what content of the panel to show
        String stringPrice, bookOrder, title;
        for (JSpinner spn : MainMenuUI.itemQty){
            qty = (int) spn.getValue();
            if(qty != 0){
                pnlItem[i].setVisible(true);
                title = MainMenuUI.title.get(j);
                bookNames[i].setText(title);
                itemQty[i].setText(String.format("(%d)", qty));
                price = MainMenuUI.price.get(j) * qty;
                stringPrice = String.format((price <= 999)? "        ₱%d" : (price <= 9999)? "      ₱%d" : "    ₱%d", price);
                itemPrices[i].setText(stringPrice);
                bookOrder = String.format("(%d) %s ₱%d", qty, title, price);
                bookOrders.add(bookOrder);
                i++;
            }
            j++;
        }
        
        int subTotal = MainMenuUI.totalPrice;
        lblSubtotal.setText(String.format("₱%d", subTotal));
        lblTotal.setText(String.valueOf(subTotal + 100));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rbtnVisa = new javax.swing.JRadioButton();
        rbtnMastercard = new javax.swing.JRadioButton();
        rbtnGcash = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCardNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        iconPaymentMethod = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblNumOfItems = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlItemList = new javax.swing.JPanel();
        pnlItem1 = new javax.swing.JPanel();
        bookName1 = new javax.swing.JLabel();
        itemPrice1 = new javax.swing.JLabel();
        itemQty1 = new javax.swing.JLabel();
        pnlItem2 = new javax.swing.JPanel();
        bookName2 = new javax.swing.JLabel();
        itemPrice2 = new javax.swing.JLabel();
        itemQty2 = new javax.swing.JLabel();
        pnlItem3 = new javax.swing.JPanel();
        bookName3 = new javax.swing.JLabel();
        itemPrice3 = new javax.swing.JLabel();
        itemQty3 = new javax.swing.JLabel();
        pnlItem4 = new javax.swing.JPanel();
        bookName4 = new javax.swing.JLabel();
        itemPrice4 = new javax.swing.JLabel();
        itemQty4 = new javax.swing.JLabel();
        pnlItem5 = new javax.swing.JPanel();
        bookName5 = new javax.swing.JLabel();
        itemPrice5 = new javax.swing.JLabel();
        itemQty5 = new javax.swing.JLabel();
        pnlItem6 = new javax.swing.JPanel();
        bookName6 = new javax.swing.JLabel();
        itemPrice6 = new javax.swing.JLabel();
        itemQty6 = new javax.swing.JLabel();
        pnlItem7 = new javax.swing.JPanel();
        bookName7 = new javax.swing.JLabel();
        itemPrice7 = new javax.swing.JLabel();
        itemQty7 = new javax.swing.JLabel();
        pnlItem8 = new javax.swing.JPanel();
        bookName8 = new javax.swing.JLabel();
        itemPrice8 = new javax.swing.JLabel();
        itemQty8 = new javax.swing.JLabel();
        pnlItem9 = new javax.swing.JPanel();
        bookName9 = new javax.swing.JLabel();
        itemPrice9 = new javax.swing.JLabel();
        itemQty9 = new javax.swing.JLabel();
        pnlItem10 = new javax.swing.JPanel();
        bookName10 = new javax.swing.JLabel();
        itemPrice10 = new javax.swing.JLabel();
        itemQty10 = new javax.swing.JLabel();
        pnlItem11 = new javax.swing.JPanel();
        bookName11 = new javax.swing.JLabel();
        itemPrice11 = new javax.swing.JLabel();
        itemQty11 = new javax.swing.JLabel();
        pnlItem12 = new javax.swing.JPanel();
        bookName12 = new javax.swing.JLabel();
        itemPrice12 = new javax.swing.JLabel();
        itemQty12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(233, 230, 230));

        jPanel2.setBackground(new java.awt.Color(233, 230, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        rbtnVisa.setBackground(new java.awt.Color(233, 230, 230));
        rbtnVisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnVisaMouseClicked(evt);
            }
        });

        rbtnMastercard.setBackground(new java.awt.Color(233, 230, 230));
        rbtnMastercard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnMastercardMouseClicked(evt);
            }
        });

        rbtnGcash.setBackground(new java.awt.Color(233, 230, 230));
        rbtnGcash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnGcashMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel1.setText("Name");

        txtName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N

        txtCardNumber.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel2.setText("Card/Gcash Number");

        jLabel3.setFont(new java.awt.Font("Street - Plain", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Payment Method");

        jPanel3.setBackground(new java.awt.Color(233, 230, 230));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel4.setText("Name");

        txtName2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N

        txtAddress.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel6.setText("Address");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel8.setText("City");

        txtCity.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel9.setText("Zip");

        txtZipCode.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Street - Plain", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Shipping Address");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(txtZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                        .addComponent(txtAddress)
                        .addComponent(txtName2))
                    .addComponent(jLabel7))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/logo-visa.png"))); // NOI18N

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/logo-mastercard.png"))); // NOI18N

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/logo-gcash.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtnVisa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(rbtnMastercard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnGcash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCardNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(rbtnMastercard))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(rbtnGcash))
                                .addComponent(label))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnVisa)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jLabel10.setText("Payment Method");

        iconPaymentMethod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPaymentMethod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/logo-visa.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        jLabel12.setText("Address");
        jLabel12.setToolTipText("");

        lblName.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 102));
        lblName.setText("Name");

        lblAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(102, 102, 102));
        lblAddress.setText("Address");

        lblNumOfItems.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        lblNumOfItems.setText("Items (2)");
        lblNumOfItems.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel18.setText("Subtotal");

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel19.setText("Shipping");

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        jLabel20.setText("Total");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("100");
        jLabel21.setToolTipText("");

        btnPay.setBackground(new java.awt.Color(255, 102, 0));
        btnPay.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Pay Now");
        btnPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPayMouseClicked(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("1199");
        lblTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotal.setText("₱10000");

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("₱");

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pnlItemList.setBackground(new java.awt.Color(249, 249, 249));

        pnlItem1.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName1.setText("Book1");
        pnlItem1.add(bookName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        itemPrice1.setText("               ₱");
        pnlItem1.add(itemPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty1.setText("(1)");
        pnlItem1.add(itemQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem2.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem2.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName2.setText("Book2");
        pnlItem2.add(bookName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice2.setText("               ₱");
        pnlItem2.add(itemPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty2.setText("(1)");
        pnlItem2.add(itemQty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem3.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem3.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName3.setText("Book3");
        pnlItem3.add(bookName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice3.setText("               ₱");
        pnlItem3.add(itemPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty3.setText("(1)");
        pnlItem3.add(itemQty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem4.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem4.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName4.setText("Book4");
        pnlItem4.add(bookName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice4.setText("               ₱");
        pnlItem4.add(itemPrice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty4.setText("(1)");
        pnlItem4.add(itemQty4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem5.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem5.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName5.setText("Book5");
        pnlItem5.add(bookName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice5.setText("               ₱");
        pnlItem5.add(itemPrice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty5.setText("(1)");
        pnlItem5.add(itemQty5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem6.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem6.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName6.setText("Book6");
        pnlItem6.add(bookName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice6.setText("               ₱");
        pnlItem6.add(itemPrice6, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty6.setText("(1)");
        pnlItem6.add(itemQty6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem7.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem7.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName7.setText("Book7");
        pnlItem7.add(bookName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice7.setText("               ₱");
        pnlItem7.add(itemPrice7, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty7.setText("(1)");
        pnlItem7.add(itemQty7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem8.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem8.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName8.setText("Book8");
        pnlItem8.add(bookName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice8.setText("               ₱");
        pnlItem8.add(itemPrice8, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty8.setText("(1)");
        pnlItem8.add(itemQty8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem9.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem9.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName9.setText("Book9");
        pnlItem9.add(bookName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice9.setText("               ₱");
        pnlItem9.add(itemPrice9, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty9.setText("(1)");
        pnlItem9.add(itemQty9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem10.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem10.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName10.setText("Book10");
        pnlItem10.add(bookName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice10.setText("               ₱");
        pnlItem10.add(itemPrice10, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty10.setText("(1)");
        pnlItem10.add(itemQty10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem11.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem11.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName11.setText("Book11");
        pnlItem11.add(bookName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice11.setText("               ₱");
        pnlItem11.add(itemPrice11, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty11.setText("(1)");
        pnlItem11.add(itemQty11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        pnlItem12.setBackground(new java.awt.Color(249, 249, 249));
        pnlItem12.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlItem12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookName12.setText("Book12");
        pnlItem12.add(bookName12, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 243, 20));

        itemPrice12.setText("               ₱");
        pnlItem12.add(itemPrice12, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, -1, 20));

        itemQty12.setText("(1)");
        pnlItem12.add(itemQty12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        javax.swing.GroupLayout pnlItemListLayout = new javax.swing.GroupLayout(pnlItemList);
        pnlItemList.setLayout(pnlItemListLayout);
        pnlItemListLayout.setHorizontalGroup(
            pnlItemListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlItem10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlItemListLayout.createSequentialGroup()
                .addGroup(pnlItemListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem6, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem7, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem8, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem9, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem11, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem12, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlItemListLayout.setVerticalGroup(
            pnlItemListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemListLayout.createSequentialGroup()
                .addComponent(pnlItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pnlItem12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlItemList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(iconPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumOfItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(62, 62, 62)
                                        .addComponent(lblSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(31, 31, 31)))
                        .addGap(30, 30, 30))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddress)
                .addGap(24, 24, 24)
                .addComponent(lblNumOfItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jLabel5.setFont(new java.awt.Font("Street - Plain", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Order Summary");

        btnDone.setText("Done");
        btnDone.setToolTipText("");
        btnDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoneMouseClicked(evt);
            }
        });
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 153, 51));
        btnBack.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnBack.setText(" ← Go back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(btnDone)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnVisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnVisaMouseClicked
        rbtnVisa.setActionCommand("VISA");
    }//GEN-LAST:event_rbtnVisaMouseClicked

    private void rbtnMastercardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnMastercardMouseClicked
        rbtnMastercard.setActionCommand("MASTERCARD");
    }//GEN-LAST:event_rbtnMastercardMouseClicked

    private void rbtnGcashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnGcashMouseClicked
        rbtnGcash.setActionCommand("GCASH");
    }//GEN-LAST:event_rbtnGcashMouseClicked

    private void btnDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoneMouseClicked
        if(paymentMethods.getSelection() == null ||
                txtName.getText().isBlank() ||
                txtCardNumber.getText().isBlank() ||
                txtName2.getText().isBlank() ||
                txtAddress.getText().isBlank() ||
                txtCity.getText().isBlank() ||
                txtZipCode.getText().isBlank())
        {
                JOptionPane.showMessageDialog(this, "Please fill up the form.");
        }
        else {
            isDone = true;
            name = txtName.getText();
            lblName.setText(name);

            date = LocalDate.now().format(DateTimeFormatter.ofPattern("MMM-dd-yyyy"));
            System.out.println(date); 

            paymentMethod = this.paymentMethods.getSelection().getActionCommand();
            System.out.println(paymentMethod);
            ImageIcon icon = new ImageIcon(String.format("C:\\Users\\Lifted Laptop\\Documents\\NetBeansProjects\\"
                    + "FinalProjectBS\\src\\Forms\\logo-%s.png", paymentMethod)); //change path 
            icon.getImage().flush();
            iconPaymentMethod.setIcon(icon);

            address = String.format("%s, %s %s", txtAddress.getText(), txtCity.getText(), txtZipCode.getText());
            lblAddress.setText(address); 
        }
    }//GEN-LAST:event_btnDoneMouseClicked

    private void btnPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayMouseClicked
        // TODO add your handling code here:
        if(isDone == false){
            JOptionPane.showMessageDialog(this, "Please fill up the form.");
        }
        else{
            int total = MainMenuUI.totalPrice + 100;
            new fileHandling().write(name, date, paymentMethod, address, bookOrders, total);

            int option = JOptionPane.showConfirmDialog(this, "Go back to main menu?", "Payment Successful!", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (option == 0){
                dispose();
                new MainMenuUI().setVisible(true);
            }  
            else
                dispose();
        } 
    }//GEN-LAST:event_btnPayMouseClicked

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed


    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        dispose();
        this.main.setVisible(true);
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckoutForm(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookName1;
    private javax.swing.JLabel bookName10;
    private javax.swing.JLabel bookName11;
    private javax.swing.JLabel bookName12;
    private javax.swing.JLabel bookName2;
    private javax.swing.JLabel bookName3;
    private javax.swing.JLabel bookName4;
    private javax.swing.JLabel bookName5;
    private javax.swing.JLabel bookName6;
    private javax.swing.JLabel bookName7;
    private javax.swing.JLabel bookName8;
    private javax.swing.JLabel bookName9;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel iconPaymentMethod;
    private javax.swing.JLabel itemPrice1;
    private javax.swing.JLabel itemPrice10;
    private javax.swing.JLabel itemPrice11;
    private javax.swing.JLabel itemPrice12;
    private javax.swing.JLabel itemPrice2;
    private javax.swing.JLabel itemPrice3;
    private javax.swing.JLabel itemPrice4;
    private javax.swing.JLabel itemPrice5;
    private javax.swing.JLabel itemPrice6;
    private javax.swing.JLabel itemPrice7;
    private javax.swing.JLabel itemPrice8;
    private javax.swing.JLabel itemPrice9;
    private javax.swing.JLabel itemQty1;
    private javax.swing.JLabel itemQty10;
    private javax.swing.JLabel itemQty11;
    private javax.swing.JLabel itemQty12;
    private javax.swing.JLabel itemQty2;
    private javax.swing.JLabel itemQty3;
    private javax.swing.JLabel itemQty4;
    private javax.swing.JLabel itemQty5;
    private javax.swing.JLabel itemQty6;
    private javax.swing.JLabel itemQty7;
    private javax.swing.JLabel itemQty8;
    private javax.swing.JLabel itemQty9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumOfItems;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlItem1;
    private javax.swing.JPanel pnlItem10;
    private javax.swing.JPanel pnlItem11;
    private javax.swing.JPanel pnlItem12;
    private javax.swing.JPanel pnlItem2;
    private javax.swing.JPanel pnlItem3;
    private javax.swing.JPanel pnlItem4;
    private javax.swing.JPanel pnlItem5;
    private javax.swing.JPanel pnlItem6;
    private javax.swing.JPanel pnlItem7;
    private javax.swing.JPanel pnlItem8;
    private javax.swing.JPanel pnlItem9;
    private javax.swing.JPanel pnlItemList;
    private javax.swing.JRadioButton rbtnGcash;
    private javax.swing.JRadioButton rbtnMastercard;
    private javax.swing.JRadioButton rbtnVisa;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
